### ISSUE TITLE
IRC-WS Improvements

### ISSUE THREAD

**Issue by stachu540** [PhilippHeuer/twitch4j#17]
### Prerequisites
* [x] ~~If this is a question/suggestion, I have already considered talking about it on [Discord](https://discord.gg/FQ5vgW3)~~
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/PhilippHeuer/twitch4j/issues) already

### Description
There is a basics of IRC-WS in #15 & #16 - now they are need impove for Moderation, `/me` interactions, `/color` changeing, and Channel Editor changes - referencing changes to README.md

### Steps to Reproduce
1. Methods for casual users (Conventional bot with limits)
 - [x] `/me` interaction chat brings text in colored - now will be like tmi.js's `action(String channel, String message)`
 - [x] `/color` picker. For non Prime/Turbo subscription will be using by Twitch default colors in enum class or like a word. (first one will be simple)
2. Methods for moderators (Give a bot, the green sword)
 - [x] Banning/Timeouting user with/without reason
 - [x] Chat mode:
   - [x] Slow
   - [x] Sub
   - [x] Folow
   - [x] Emote Only
   - [x] R9K
3. Methods for Channel Editor (Bot as Editor? If you know what you doing)
 - [x] Commercials
 - [x] Host mode
4. Adding methods where they using API query for getting information about user information in chat via endpoint `https://api.twitch.tv/kraken/users/<uid>/chat` - where `<uid>` is **user id**. [More info](https://discuss.dev.twitch.tv/t/have-a-chat-whisper-bot-let-us-know/10651)
 - [x] it is known bot method returns boolean
 - [x] increasing message bucket from 20 to 50 if `is_known_bot` is `true`

**Expected behavior:** Using referenced `MessageInterface` method, must be gave access more methods if aboved requirements was met.

**Actual behavior:** Gaving access for more methods, if aboved requirements was met, otherwise will thrown Custom exception stacktrace.

**Stacktrace (if applicable):** Custom stacktracing if aboved requirements will not met

**Version affected:** from `feature\tmi` branch, otherwise `develop` branch if #15 and #16 will merged there.

### Additional Information
For the booth PR's #15 and #16 `MessageInterface` will be improved with chat interactions as Mod or Editor, and convectional daily usage elements (`/color` and `/me`). After #16 is finished, I will starting work for Improving steps above mentioned.

**Comment by PhilippHeuer** [comment]
We don't need commercials over irc, since there is a rest api to trigger them. The remaining points are good and need to be added.

**Comment by stachu540** [comment]
You can trigger commercials without API access. Using `/commercial` command triggering on channel commercials. Works only for Channel Editors added on [Editors tab in Dashboard](https://www.twitch.tv/dashboard/permissions).

If you wish, I can remove this one.

**Comment by stachu540** [comment]
Added information about increasing default message bucket. You will find information on top of this post

**Comment by stachu540** [comment]
Redirecting question from #20: Where should I put it? Into separate class or somewhere?
