### ISSUE TITLE
twitch stream key

### ISSUE THREAD

**Issue by mhackeras** [PhilippHeuer/twitch4j#25]
i wonder if its possible to retrieve stream key.. or if u could add the possibility to do that

**Comment by PhilippHeuer** [comment]
You can use the `twitchClient.getChannelEndpoint("channelName").getChannelPrivilegied()` Method to get more information than with the default getChannel(). You can then use `channel.getStreamKey()` to get the stream key. This requires the `channel_read` scope.

The new helix api does not support returning stream keys right now - so this feature might vanish once we upgrade to helix if they didn't add it until then.
